# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergey/code/flow_reader_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergey/code/flow_reader_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergey/code/flow_reader_cpp/CMakeFiles /home/sergey/code/flow_reader_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergey/code/flow_reader_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flow_reader

# Build rule for target.
flow_reader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flow_reader
.PHONY : flow_reader

# fast build rule for target.
flow_reader/fast:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/build
.PHONY : flow_reader/fast

Dbscan.o: Dbscan.cpp.o

.PHONY : Dbscan.o

# target to build an object file
Dbscan.cpp.o:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/Dbscan.cpp.o
.PHONY : Dbscan.cpp.o

Dbscan.i: Dbscan.cpp.i

.PHONY : Dbscan.i

# target to preprocess a source file
Dbscan.cpp.i:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/Dbscan.cpp.i
.PHONY : Dbscan.cpp.i

Dbscan.s: Dbscan.cpp.s

.PHONY : Dbscan.s

# target to generate assembly for a file
Dbscan.cpp.s:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/Dbscan.cpp.s
.PHONY : Dbscan.cpp.s

Xycut.o: Xycut.cpp.o

.PHONY : Xycut.o

# target to build an object file
Xycut.cpp.o:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/Xycut.cpp.o
.PHONY : Xycut.cpp.o

Xycut.i: Xycut.cpp.i

.PHONY : Xycut.i

# target to preprocess a source file
Xycut.cpp.i:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/Xycut.cpp.i
.PHONY : Xycut.cpp.i

Xycut.s: Xycut.cpp.s

.PHONY : Xycut.s

# target to generate assembly for a file
Xycut.cpp.s:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/Xycut.cpp.s
.PHONY : Xycut.cpp.s

common.o: common.cpp.o

.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i

.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s

.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/common.cpp.s
.PHONY : common.cpp.s

flow.o: flow.cpp.o

.PHONY : flow.o

# target to build an object file
flow.cpp.o:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/flow.cpp.o
.PHONY : flow.cpp.o

flow.i: flow.cpp.i

.PHONY : flow.i

# target to preprocess a source file
flow.cpp.i:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/flow.cpp.i
.PHONY : flow.cpp.i

flow.s: flow.cpp.s

.PHONY : flow.s

# target to generate assembly for a file
flow.cpp.s:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/flow.cpp.s
.PHONY : flow.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/flow_reader.dir/build.make CMakeFiles/flow_reader.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... flow_reader"
	@echo "... edit_cache"
	@echo "... Dbscan.o"
	@echo "... Dbscan.i"
	@echo "... Dbscan.s"
	@echo "... Xycut.o"
	@echo "... Xycut.i"
	@echo "... Xycut.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... flow.o"
	@echo "... flow.i"
	@echo "... flow.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

